### PR TITLE
feat: Use Detail Panel from Language Server

### PR DESCRIPTION
**Pull request by PeterSchafer**
### Description
Language Server sends an HTML Detail panel, which can be shown directly instead of constructing it in the IDE itself.

### Checklist

- [ ] Tests added and all succeed
- [ ] Linted
- [ ] CHANGELOG.md updated
- [ ] README.md updated, if user-facing

### CODE REVIEW

**Comment by bastiandoetsch** [comment]
Side by side screeenshots:
image
image

**Comment by bastiandoetsch** [comment]
I'm aware that the fixes probably are on the LS side - where should we collect discrepancies?

**Comment by PeterSchafer** [comment]
> I'm aware that the fixes probably are on the LS side - where should we collect discrepancies?

yes we found in bug in the LS implementation that handles the discrepancies in the details path

**Comment by PeterSchafer** [comment]
let's look at the discrepancies together, from the screenshots, I'm not completely sure what is meant.

**Review by j-luong — APPROVED** [review]

**Pull request merged**
