### PR TITLE
fix: file opening on windows [HEAD-168]

### PR DESCRIPTION
**Pull request by asaf92**
### Description

Fixed document opening when using windows paths.

### CODE REVIEW

**Review by bastiandoetsch — COMMENTED** [review]
Could you please add a test to verify the expected behaviour?

**Comment by asaf92** [comment]
> Could you please add a test to verify the expected behaviour?

I think we can't test code that uses the vscode API

**Review by michelkaporin — APPROVED** [review]
Please test the change with remote dev environments before merging it in. 🙏

**Comment by michelkaporin** [comment]
> I think we can't test code that uses the vscode API

That's correct. We could write an integration test here but this path hasn't been paved well with our product scanners yet.

**Pull request merged**
