### PR TITLE
fix: updated code-client version improved network outage tolerance

### PR DESCRIPTION
**Pull request by Arvi3d**
Bumped version of @snyk/code-client that should help tolerating network issues.
Related ticket in Snyk code : https://snyksec.atlassian.net/browse/COD-571

### CODE REVIEW

**Review by bastiandoetsch — APPROVED** [review]

**Comment by Arvi3d** [comment]
thank you @bastiandoetsch 
Would you please merge and release a new version?

**Comment by michelkaporin** [comment]
@Arvi3d please include ticket reference next time as part of PR. This would be easier for us to see what was the change that was addressed by bumping the version. How time sensitive is the version release?

**Comment by Arvi3d** [comment]
not urgent. when you have time...

**Comment by michelkaporin** [comment]
@Arvi3d I'll ping you as soon as we release. Probably during this week.

**Pull request merged**
