### PR TITLE
feat: OSS webview tab - overview section [ROAD-289]

### PR DESCRIPTION
**Pull request by michelkaporin**
Screenshot 2021-09-02 at 16 10 41

### CODE REVIEW

**Comment by michelkaporin** [comment]
@aldanchenko please take a look in @pavel-snyk's absence 👼

**Review by aldanchenko — APPROVED** [review]
LGTM 👍

**Comment by sharonsit** [comment]
LGTM.
Did you mean to also commit the `package-lock` file?

**Comment by michelkaporin** [comment]
@sharonsit yes, it is needed to restore the dependency tree correctly.

**Pull request merged**
